### ISSUE TITLE
go get -u -v github.com/codesenberg/bombardier errror

### ISSUE THREAD

**Issue by PhanSon95** [codesenberg/bombardier#44] opened 2018-12-26 02:58 UTC
When i run this command "go get -u -v github.com/codesenberg/bombardier" i get error 

```
package github.com/codesenberg/bombardier/vendor/golang.org/x/net/http2:
vendor/golang.org/x/net/http2/pipe.go:1:1: expected 'package', found 'EOF'
```
Please give me a solution, thanks you so much|
[From MacOS]

**Comment by codesenberg** [comment] 2018-12-26 10:09
Hmm... I think might be some MacOS-specific issue or something. Also, are you sure you pasted the whole output of `go get -u -v github.com/codesenberg/bombardier`? What version of Go are you using?

**Comment by akshaybabloo** [comment] 2019-10-26 10:04
I get the same error. I am using Go version 1.13

**Comment by kataras** [comment] 2019-11-02 20:12
Same here

**Comment by kataras** [comment] 2019-11-02 20:19
Same here.

@codesenberg the problem is that `go get -u` will grab the `github.com/cheggaaa/pb v2.0.7+incompatible`. **The solution is one of the below:**

**1.** to replace: https://github.com/codesenberg/bombardier/blob/9a0fa99d0334574700f31150c9d72a3eefc05092/bombardier.go#L17
with: `"github.com/cheggaaa/pb/v3"` and update the code.
**2.** Create a `go.mod` file inside this repository which will grab the `v1` version or a pseudo-commit version of the `pb` library.
**3.** Create a `go.mod` file inside this repository and add `replace github.com/cheggaaa/pb => github.com/cheggaaa/pb v1.0.29-0.20190701083823-9f3292738157`

**Comment by akshaybabloo** [comment] 2019-11-02 20:28
The binary file doesn’t work too for some reason

**Comment by lriverawong** [comment] 2020-03-26 00:18
Any updates on this getting fixed on master?

**Comment by maxim-ge** [comment] 2020-07-08 10:52
Having the same problem as @akshaybabloo

**Comment by codesenberg** [comment] 2020-10-04 16:01
@kataras seems unlikely. All dependencies are vendored, so `go get` shouldn't be grabbing anything, unless Go changed the way it handles vendored dependencies. The output @akshaybabloo provided is very weird. I just checked and for me clean `go get` is doing just this:

```bash
$ go get -u -v github.com/codesenberg/bombardier
github.com/codesenberg/bombardier (download)
```

Even weirder that binary is not working too. No ideas what might be going on here.

**Comment by kataras** [comment] 2020-10-04 17:00
@codesenberg I can confirm that it's working now, tested three days ago with: https://github.com/kataras/iris/tree/master/_benchmarks/view#how-to-run

**Comment by codesenberg** [comment] 2020-10-14 16:49
So I was able to dig a bit and the cause for this is a different flag - `GO111MODULE`.
If it's set to `on` then `go get` will ignore (it seems) `vendor` directory and try to fetch stuff from Github.
If anyone encounters same issue in the future a way to workaround this is to set `GO111MODULE` to `off`:
```bash
$ GO111MODULE=off go get -u github.com/codesenberg/bombardier
```
I'll try to work on adding a `.mod` file in meanwhile, but there's a minor blocker: [link](https://github.com/codesenberg/bombardier/pull/53#issuecomment-593024725).

**Closed by codesenberg** 2020-10-14 16:49 UTC
Labels: question
