### ISSUE TITLE
Panic starting 1.02 Windows 386 version

### ISSUE THREAD

**Issue by morganbr** [codesenberg/bombardier#18] opened 2017-05-04 04:12 UTC
The Windows 386 1.02 build fails to start sending requests with the output below. The x64 version seems to work for me. I'm running Windows 10 x64 and using the exes from the releases.

```bash
> bombardier-windows-386.exe http://localhost:5000/json
Bombarding http://localhost:5000/json for 10s using 125 connections
[-----------------------------------------------------------------------------]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x44cddc]

goroutine 71 [running]:
sync/atomic.AddUint64(0x1119ac94, 0x98, 0x0, 0x1, 0x69d57d)
        C:/Go/src/sync/atomic/asm_386.s:112 +0xc
main.(*bombardier).writeStatistics(0x1119ac30, 0x1b, 0x0, 0x98, 0x0, 0xc8, 0xb3b0, 0x0)
        C:/Users/frei/Documents/Go/Workspaces/Default/src/codesenberg/bombardier/bombardier.go:140 +0x59
main.(*bombardier).performSingleRequest(0x1119ac30)
        C:/Users/frei/Documents/Go/Workspaces/Default/src/codesenberg/bombardier/bombardier.go:167 +0xe1
main.(*bombardier).worker(0x1119ac30)
        C:/Users/frei/Documents/Go/Workspaces/Default/src/codesenberg/bombardier/bombardier.go:172 +0x3c
main.(*bombardier).bombard.func1(0x1119ac30)
        C:/Users/frei/Documents/Go/Workspaces/Default/src/codesenberg/bombardier/bombardier.go:234 +0x48
created by main.(*bombardier).bombard
        C:/Users/frei/Documents/Go/Workspaces/Default/src/codesenberg/bombardier/bombardier.go:235 +0xed
```

**Comment by codesenberg** [comment] 2017-05-04 08:38
Thanks for the report. I think I know what the problem is. Gonna release **v1.03** with the fix for this in a day or two, maybe, even today.

**Comment by codesenberg** [comment] 2017-05-04 11:25
@morganbr, check out [v1.0.3](https://github.com/codesenberg/bombardier/releases/tag/v1.0.3) it should be fixed now.

**Comment by morganbr** [comment] 2017-05-04 18:55
@codesenberg  that fixed it. Thanks!

**Closed** 2017-05-05 08:11 UTC
Labels: bug
